name: My first Workflow

on: push

jobs:
    Second_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4    

        - name: List and Read files 
          run: |
            echo "My first Guthub Actions Job"
            ls -al
            cat README.md 

        - name: Generate ASCII Artwork 
          run: cowsay -f dragon "Run for cover, I am a Dragon......RAWR" >> dragon.txt

            
        #- name: List Files
        #  run: ls
          
        #- name: Read File
        #  run: cat README.md  