name: Generate ASCII Artwork2

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4 
          
        - name: Make script executable
          run: chmod +x script.sh
        
        - name: List files in the working directory
          run: ls -l
  
        - name: Run ASCII script
          run: ./script.sh