name: Generate ASCII Artwork2

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4 
          
        - name: List and Read files 
          run: |
            echo "My first Guthub Actions Job"
            ls -al
            cat README.md 

        - name: Executing Shell Script
          run: |
            chmod +x ascii-script.sh 
            ./ascii-script.sh

       