name: Run ASCII Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the working directory (Debugging step)
        run: ls -la

      - name: Make script executable
        run: chmod +x ascii-script.sh  # Adjust path if needed

      - name: Run the script
        run: ./ascii-script.sh  # Adjust path if needed
